### ISSUE TITLE
(from Salmonia3+) cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MegaBlaziken** [zhxie/conch-bay#10]
I am Japanese and use machine translation.

Yesterday I installed conch-bay for the first time.
So I saved a backup of my data from the settings of Salmonia3+ (version 2.1.6) and tried to import the saved json file with conch-bay.
However,
`Cannot read property 'length' of undefined`
was displayed and I could not do it.

I would also like to export the data in conch-cay, but would this be in SplatNet format?

This is my first time using Github Issues, so I apologize if I said something inappropriate.

**Comment by zhxie** [comment]
Thanks for using Conch Bay. Conch Bay does not support importing Salmonia3+ format directly since Salmonia3+ trimmed some data, and requires an additional conversion. You have to convert the exported JSON with [the script](https://github.com/zhxie/conch-bay#import-data-from-salmonia3).

Conch Bay stores and exports results in exactly SplatNet 3 format.

If you have difficulty converting results or have any further question, you can reach us with mail by clicking the "Support" link in the bottom of the app, then pressing on "Send a mail".

リザルトの変換に問題がある場合、またはさらに質問がある場合は、アプリの下部にある [サポート] リンクをクリックし、[メールを送る] をクリックしてメールでお問い合わせください。日本語OK。

**Comment by zhxie** [comment]
Fixed by [3d14d64](https://github.com/zhxie/conch-bay/commit/3d14f64bfa381c3a59f2d20fe7f41db6a7c10068).
