### ISSUE TITLE
How to convert a conch-bay-export json file into a conch-bay-import file?

### ISSUE THREAD

**Issue by EmrysQ** [zhxie/conch-bay#30]
Before I uninstalled conch bay, I exported a conch-bay-export json file. But when I tried to import this file, it said **'JSON Parse error: Unexpected character:{'**. So how could I convert the export file into a import file?

**Comment by zhxie** [comment]
Actually there is a bug of exporting in v1.10.0. Please select "Split and Import" on importing. You can also send the mail to us for help via the support in the bottom of the home screen.

Due to Nintendo's negative attitude towards 3rd-party apps, we no longer update Conch Bay in the store since v1.10.0. You can update it through TestFlight (iOS) or download unsigned APKs in Actions (Android). Thanks for your understanding.
